import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import Screen from '@/shared/components/Screen';
import Card from '@/shared/components/Card';
import Button from '@/shared/components/Button';
import { PLAYER_COLORS, useJeopardyStore } from '../store';
import { ALL_PACKS } from '../data/packs';
export default function Setup() {
    const { pack, selectedPackId, selectPack, players, addPlayer, removePlayer, renamePlayer, startGame, } = useJeopardyStore();
    const canStart = players.length >= 2 && players.every((p) => p.name.trim());
    const hasMultiplePacks = ALL_PACKS.length > 1;
    return (_jsx(Screen, { children: _jsxs("div", { className: "w-full max-w-3xl", children: [_jsxs("header", { className: "flex items-center justify-between mb-8 gap-3", children: [_jsx(Link, { to: "/", className: "glass rounded-full px-4 py-2 text-ink hover:text-bark text-sm font-medium shadow-soft", children: "\u2190 \u0412 \u043B\u043E\u0431\u0431\u0438" }), _jsx("h1", { className: "glass rounded-2xl px-6 py-2 font-display text-2xl sm:text-3xl font-bold text-ink shadow-soft", children: "\u0421\u0432\u043E\u044F \u0438\u0433\u0440\u0430" }), _jsx("div", { className: "w-24 hidden sm:block" })] }), _jsxs(Card, { pad: "lg", className: "mb-6", children: [_jsxs("div", { className: "flex items-baseline justify-between mb-4", children: [_jsx("h2", { className: "font-display text-xl font-semibold", children: "\u0418\u0433\u0440\u043E\u043A\u0438" }), _jsx("span", { className: "text-muted text-sm", children: "\u043E\u0442 2 \u0434\u043E 6" })] }), _jsx("div", { className: "space-y-3", children: players.map((p) => {
                                const col = PLAYER_COLORS.find((c) => c.id === p.color);
                                return (_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "w-3 h-3 rounded-full shrink-0", style: { backgroundColor: col.hex } }), _jsx("input", { value: p.name, onChange: (e) => renamePlayer(p.id, e.target.value), className: "flex-1 bg-cream/60 rounded-xl px-4 py-2.5 outline-none focus:bg-cream", placeholder: "\u0418\u043C\u044F \u0438\u0433\u0440\u043E\u043A\u0430" }), players.length > 2 && (_jsx("button", { onClick: () => removePlayer(p.id), className: "text-muted hover:text-rose-dark text-sm px-2", "aria-label": "\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u0438\u0433\u0440\u043E\u043A\u0430", children: "\u2715" }))] }, p.id));
                            }) }), players.length < 6 && (_jsx("button", { onClick: () => addPlayer(), className: "mt-4 text-[#566849] hover:text-[#7A8F6A] text-sm font-medium", children: "+ \u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0438\u0433\u0440\u043E\u043A\u0430" }))] }), _jsxs(Card, { pad: "lg", className: "mb-6", children: [hasMultiplePacks ? (_jsx("div", { className: "grid sm:grid-cols-2 gap-3", children: ALL_PACKS.map((p) => {
                                const active = p.id === selectedPackId;
                                const totalQ = p.rounds.reduce((s, r) => s + r.themes.reduce((a, t) => a + t.questions.length, 0), 0);
                                return (_jsxs("button", { onClick: () => selectPack(p.id), className: [
                                        'text-left rounded-2xl p-4 border-2 transition-all',
                                        active
                                            ? 'border-[#566849] bg-[#7A8F6A]/10'
                                            : 'border-ink/5 bg-cream/40 hover:border-ink/15',
                                    ].join(' '), children: [_jsxs("div", { className: "flex items-baseline gap-2 mb-1", children: [p.emoji && _jsx("span", { className: "text-xl", children: p.emoji }), _jsx("span", { className: "font-display font-bold", children: p.title })] }), p.description && (_jsx("div", { className: "text-muted text-sm leading-snug mb-2", children: p.description })), _jsxs("div", { className: "text-muted text-xs", children: [p.rounds.length, " \u0440\u0430\u0443\u043D\u0434", p.rounds.length === 1 ? '' : p.rounds.length < 5 ? 'а' : 'ов', " \u00B7", ' ', p.rounds[0].themes.length, " \u0442\u0435\u043C \u00B7 ", totalQ, " \u0432\u043E\u043F\u0440\u043E\u0441\u043E\u0432"] })] }, p.id));
                            }) })) : (_jsxs("div", { className: "flex items-baseline gap-2 mb-1", children: [pack.emoji && _jsx("span", { className: "text-xl", children: pack.emoji }), _jsx("span", { className: "font-display text-2xl font-bold", children: pack.title })] })), _jsxs("div", { className: "mt-4", children: [_jsx("div", { className: "text-muted text-xs uppercase tracking-wider mb-2", children: "\u0422\u0435\u043C\u044B \u043F\u0435\u0440\u0432\u043E\u0433\u043E \u0440\u0430\u0443\u043D\u0434\u0430" }), _jsx("div", { className: "grid sm:grid-cols-2 gap-2", children: pack.rounds[0].themes.map((t) => (_jsxs("div", { className: "flex items-center gap-2 bg-cream/60 rounded-xl px-3 py-2", children: [_jsx("span", { className: "text-xl", children: t.emoji }), _jsx("span", { className: "text-sm font-medium", children: t.name }), _jsxs("span", { className: "text-muted text-xs ml-auto", children: [t.questions.length, " \u0432\u043E\u043F\u0440."] })] }, t.name))) })] })] }), _jsx(Button, { variant: "primary", size: "xl", fullWidth: true, disabled: !canStart, onClick: startGame, children: "\u041D\u0430\u0447\u0430\u0442\u044C \u0438\u0433\u0440\u0443" })] }) }));
}
